### ISSUE TITLE
MOCKUP

### ISSUE THREAD

**Issue by sophalS** [sophalS/2022-QUIZ-APP-G7#2]
TIME = 2 hours

**1 menu bar** with 2 items (EDT QUI / RUN QUIZ)

**2 views:**
- EDIT THE QUIZ  (create /edit / remove question
- RUN THE QUIZ ( select answer + click on submit)

STEPS
1 - brainsotrming  : Everyone comes with 3 ideas and the team select  the best design
2 - figma
3 post hte mock up on github

**Comment by meng-mao** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/92765124/150501354-5d4dc67c-e6a4-4f3b-b66a-77c112a77a55.jpg)
Is it okay?  @ronanpnc

**Comment by Keanhor2** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/90302802/150520610-f3db460f-518f-4ace-a489-34f5dc6c913e.jpg)
Here is our menu @ronanpnc
